### ISSUE TITLE
Multipart form failing

### ISSUE THREAD

**Issue by dwaynemac** [typhoeus/typhoeus#213]
I'm trying to submit a file with Typhoeus (worked in 0.2.4) and I'm getting this error:

```
NoMethodError (undefined method `bytesize' for nil:NilClass)
```

It happens in ethon-0.4.2/lib/ethon/easies/form.rb:95
